controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    cartpole_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    x_controller:
      type: effort_controllers/JointGroupEffortController

x_controller: 
  ros__parameters:
    joints:  
      - cart_to_pole1  
    command_interfaces:  
      - effort  
    state_interfaces:  
      - position  
      - velocity  
      - effort  
    use_sim_time: true
