controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    cartpole_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    x_controller:
      type: effort_controllers/JointGroupEffortController


x_controller:
  ros__parameters:
    joints:
      - base_to_plat
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
