controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    cartpole_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    x_controller:
      type: effort_controllers/JointEffortController
      use_sim_time: true
